included: # paths to include during linting. `--path` is ignored if present.
  - CybridSDK
  - CybridSDKTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - CybridSDKTestApp

indentation: 2

opt_in_rules: # These rules are disabled by default, unless explicitly added below.
  - anyobject_protocol
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - discouraged_optional_boolean
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - for_where
  - force_try
  - generic_type_name
  - identical_operands
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_unit_test
  - private_outlet
  - prohibited_super_call
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - redundant_type_annotation
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  # - trailing_whitespace
  - type_contents_order
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_declaration
  - valid_ibinspectable
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate
  - xctfail_message
  - yoda_condition

anyobject_protocol:
  severity: error
array_init:
  severity: error
block_based_kvo:
  severity: error
class_delegate_protocol:
  severity: error
closing_brace:
  severity: error
closure_end_indentation:
  severity: error
closure_parameter_position:
  severity: error
closure_spacing:
  severity: error
collection_alignment:
  severity: error
colon:
  severity: error
comma:
  severity: error
compiler_protocol_init:
  severity: error
contains_over_first_not_nil:
  severity: error
control_statement:
  severity: error
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
discouraged_object_literal:
  severity: error
discouraged_optional_boolean:
  severity: error
dynamic_inline:
  severity: error
empty_count:
  severity: error
empty_enum_arguments:
  severity: error
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
empty_string:
  severity: error
empty_xctest_method:
  severity: warning
fatal_error_message:
  severity: error
first_where:
  severity: error
for_where:
  severity: error
force_try:
  severity: error
generic_type_name:
  severity: error
identical_operands:
  severity: error
implicit_getter:
  severity: error
inert_defer:
  severity: error
is_disjoint:
  severity: error
joined_default_parameter:
  severity: error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
literal_expression_end_indentation:
  severity: error
lower_acl_than_parent:
  severity: error
mark:
  severity: error
modifier_order:
  severity: error
multiline_arguments:
  severity: error
multiline_function_chains:
  severity: error
multiline_literal_brackets:
  severity: error
multiline_parameters:
  severity: error
nimble_operator:
  severity: error
opening_brace:
  severity: error
operator_usage_whitespace:
  severity: error
operator_whitespace:
  severity: error
overridden_super_call:
  severity: warning
override_in_extension:
  severity: error
pattern_matching_keywords:
  severity: error
private_action:
  severity: error
private_unit_test:
  severity: error
prohibited_super_call:
  severity: error
redundant_discardable_let:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
shorthand_operator:
  severity: error
single_test_class:
  severity: error
sorted_first_last:
  severity: error
statement_position:
  severity: error
static_operator:
  severity: error
switch_case_alignment:
  severity: error
switch_case_on_newline:
  severity: error
syntactic_sugar:
  severity: error
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
type_contents_order:
  severity: error
unavailable_function:
  severity: error
unneeded_break_in_switch:
  severity: error
unneeded_parentheses_in_closure_argument:
  severity: error
untyped_error_in_catch:
  severity: error
unused_closure_parameter:
  severity: error
unused_enumerated:
  severity: error
unused_import:
  severity: error
unused_optional_binding:
  severity: error
unused_declaration:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace:
  severity: error
weak_delegate:
  severity: error
xctfail_message:
  severity: error
yoda_condition:
  severity: error

file_length:
  warning: 1000
  error: 1200

#identifier_name:
#  excluded:
#    - id
#    - URL

large_tuple:
  warning: 3

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

nesting:
  severity: error
  type_level: 10

private_outlet:
  severity: error
  allow_private_set: true

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]

reporter: "xcode"
