codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "CybridSDK/CybridSDK.h"
  - "CybridSDK.docc/*"
  - "CybridSDKTests/**/*"
  - "**/*Cell.swift"
  - "**/*View.swift"
  - "**/*Modal.swift"
  - "CybridSDK/Components/Component.swift"
  - "CybridSDK/Components/**/*View+Extensions.swift"
  - "**/*ViewController.swift"
  - "**/*ViewController+Extensions.swift"
  - "CybridSDK/Components/Trade/View/TradeViewModel.swift"
  - "CybridSDK/Components/ListPrices/View/ListPricesViewModel.swift"
  - "CybridSDK/Components/AccountsComponent/Entity/AccountAssetPriceModel.swift"
  - "CybridSDK/Framework Extensions/Model/*"
  - "CybridSDK/Framework Extensions/UIView/*"
  - "CybridSDK/Utilities/ImageUtils.swift"
  - "CybridSDK/Utilities/ReusableViews/*"
  - "CybridSDK/Utilities/ReusableViews/**/*"
  - "CybridSDK/Utilities/Formatters/BigDecimalValidator"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
