codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "CybridSDK/CybridSDK.h"
  - "CybridSDK.docc/*"
  - "CybridSDKTests/*"
  - "**/*Tests.swift"
  - "**/*NavigationController.swift"
  - "**/*ViewController.swift"
  - "**/*View.swift"
  - "**/*Cell.swift"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: true
