version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  swiftlint: ngs/swiftlint@0.0.1

jobs:

  swiftlint:
    description: Runs swiftlint
    executor: swiftlint
    steps:
      - checkout
      - run: "swiftlint lint --reporter junit | tee result.xml"
      - store_artifacts:
          path: "result.xml"
      - store_test_results:
          path: "result.xml"

  pod-spec-lint:
    description: Runs podspec lint
    macos:
      xcode: "14.0.1"
    steps:
      - checkout
      - run:
          name: "Run CocoaPods Podspec linter"
          command: "pod spec lint --verbose --quick"

  build-and-test:
    macos:
      xcode: "14.0.1"
    environment:
      FASTLANE_OUTPUT_DIR: "./fastlane/output"
    steps:
      - checkout
      - run:
          name: "Install CocoaPods"
          no_output_timeout: 3m
          command: "pod install --verbose"
      - run:
          name: "Build and run tests"
          command: "fastlane test output_directory:$FASTLANE_OUTPUT_DIR/"
      - codecov/upload:
          file: "$FASTLANE_OUTPUT_DIR/cobertura.xml"

  publish:
    macos:
      xcode: "14.0.1"
    steps:
      - checkout
      - run:
          name: "Install CocoaPods"
          no_output_timeout: 3m
          command: "pod install --verbose"
      - run:
          name: "Upload App to Appetize"
          command: "fastlane run build_and_upload_to_appetize scheme:CybridSDKTestApp api_token:${APPETIZE_API_TOKEN} public_key:${APPETIZE_PUBLIC_API_TOKEN}"

executors:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest

workflows:
  ios-workflow:
    jobs:
      - swiftlint
      - pod-spec-lint
      - build-and-test
      - publish:
          filters:
            branches:
              only:
                - main
