version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  ios-build-and-test:
    macos:
      xcode: "13.3.1"
    environment:
      FL_OUTPUT_DIR: "./fastlane/output/"

    steps:
      - checkout
      - run:
          name: "Install CocoaPods"
          command: "pod install --verbose"
      - run:
          name: "Build and run tests"
          command: "fastlane test output_directory:'./fastlane/output/'"
      - codecov/upload:
          file: "./fastlane/output/cobertura.xml"

workflows:
  ios-workflow:
    jobs:
      - ios-build-and-test
