# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs tests"
  lane :test do |options|
    xcversion(version: "14.1.0")
    outputPath = options[:output_directory]
    scan(
      scheme: "CybridSDK",
      workspace: "CybridSDK.xcworkspace",
      code_coverage: true,
      devices: ["iPhone 13 Pro"]
    )
    slather(
      scheme: "CybridSDK",
      circleci: true,
      cobertura_xml: true,
      output_directory: outputPath,
      proj: "CybridSDK.xcodeproj",
      workspace: "CybridSDK.xcworkspace",
      ignore: [
        'Pods/*'
      ]
    )
  end

end
