# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs tests"
  lane :test do
    scan(
      workspace: "CybridSDK.xcworkspace",
      devices: ["iPhone SE (2nd Generation) (13.0)", "iPhone 6s (14.0)", "iPhone 8 (14.5)", "iPhone 11 (15.0)", "iPhone 12 Pro (13.5)", "iPhone 13 Pro Max (15.0)"]
    )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(export_method: "ad-hoc")
  end
end
