# This is a basic workflow that is manually triggered

name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
       version:
        description: 'Version  (i.e. 1.1.3)'
        required: true
env:
  GIT_ACTOR: jc-cybrid
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Bundle Install
      run: bundle install
    - name: Add Pod Spec
      run: pod repo add cybrid-podspec https://${{ env.GIT_ACTOR }}:${{ secrets.GIT_TOKEN }}@github.com/Cybrid-app/cybrid-podspecs.git
    - name: Bump Podspec version
      run: fastlane run version_bump_podspec path:"CybridSDK.podspec" version_number:${{ github.event.inputs.version }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Release/${{ github.event.inputs.version }}
        base: main
        branch: Release/${{ github.event.inputs.version }}
        body: |
          Release: ${{ github.event.inputs.version }}
          Changes:
          - Bump version to ${{ github.event.inputs.version }}
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        commitish: Release/${{ github.event.inputs.version }}
        tag_name: "${{ github.event.inputs.version }}"
        release_name: "${{ github.event.inputs.version }}"
        body: "${{ github.event.inputs.version }}"
        commit-message: "Bump pod version"
    - name: Push Pod Spec
      run: pod repo push cybrid-podspec CybridSDK.podspec
